# Generated by Django 5.2.8 on 2025-11-17 17:07

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PB_Assistant', '0001_create_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('time_edited', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('title_slug', models.SlugField(blank=True, max_length=512, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('author_list', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetaryBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('query', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('source_documents', models.JSONField(blank=True, null=True)),
                ('chunk_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPaperText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hasfulltext', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academicpaper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academicpaper_text', to='PB_Assistant.academicpaper')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPaperPlanetaryBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PB_Assistant.academicpaper')),
                ('planetary_boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PB_Assistant.planetaryboundary')),
            ],
        ),
        migrations.AddField(
            model_name='academicpaper',
            name='planetary_boundary',
            field=models.ManyToManyField(through='PB_Assistant.AcademicPaperPlanetaryBoundary', to='PB_Assistant.planetaryboundary'),
        ),
        migrations.CreateModel(
            name='AcademicPaperTextEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('academicpaper_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicpaper_embeddings', to='PB_Assistant.academicpapertext')),
            ],
            options={
                'unique_together': {('academicpaper_text', 'chunk_index')},
            },
        ),
    ]
