# Generated by Django 5.2.8 on 2025-12-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Assistant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpaper',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicpaper',
            name='publication_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
