# Generated by Django 5.2.8 on 2026-01-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PB_Assistant", "0003_searchfolder_searchhistory_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchfolder",
            name="color",
            field=models.CharField(blank=True, default="#6c757d", max_length=20),
        ),
    ]
